<?php

namespace App\Services;

use App\Models\ActivityLog;
use App\Models\User;
use App\Notifications\SecurityAnomalyAlert;
use Carbon\Carbon;
use Illuminate\Support\Facades\Notification;
use Illuminate\Support\Facades\Schema;

class SecurityAnomalyService
{
    /**
     * Check if failed logins for a given IP or Email exceed the threshold.
     */
    public function checkFailedLoginThreshold(string $email, ?string $ip): void
    {
        $threshold = (int) config('audit.failed_login_threshold', env('AUDIT_FAILED_LOGIN_THRESHOLD', 5));
        $windowMinutes = (int) config('audit.failed_login_window_minutes', 10);
        $since = Carbon::now()->subMinutes($windowMinutes);

        $failedCount = ActivityLog::where('event_category', 'security')
            ->where('action', 'failed_login')
            ->where('created_at', '>=', $since)
            ->where(function ($q) use ($email, $ip) {
                $q->where('description', 'like', "%{$email}%");
                if ($ip) {
                    $q->orWhere('ip_address', $ip);
                }
            })
            ->count();

        // If threshold reached (e.g. exactly at threshold or multiples to avoid spamming)
        if ($failedCount >= $threshold && $failedCount % $threshold === 0) {
            $this->dispatchAlert(
                anomalyType: 'brute_force_login',
                title: "Multiple Failed Login Attempts ({$failedCount} failures in {$windowMinutes} mins)",
                description: "We detected {$failedCount} consecutive failed login attempts targeting {$email} from IP {$ip}.",
                metadata: [
                    'target_email' => $email,
                    'source_ip' => $ip ?? 'Unknown',
                    'failures_count' => $failedCount,
                    'time_window' => "{$windowMinutes} minutes",
                ]
            );
        }
    }

    /**
     * Check and alert on privilege escalation (promotion to admin / super-admin).
     */
    public function checkPrivilegeEscalation(User $targetUser, string $newRole, ?User $actor = null): void
    {
        $adminRoles = ['admin', 'super-admin', 'superadmin', 'manager'];

        if (in_array(strtolower($newRole), $adminRoles, true)) {
            $actorName = $actor ? "{$actor->name} ({$actor->email})" : 'System/CLI';

            $this->dispatchAlert(
                anomalyType: 'privilege_escalation',
                title: "User Role Elevated to {$newRole}",
                description: "User {$targetUser->name} ({$targetUser->email}) was granted administrative role '{$newRole}' by {$actorName}.",
                metadata: [
                    'affected_user_id' => $targetUser->id,
                    'affected_user' => $targetUser->name,
                    'new_role' => $newRole,
                    'authorized_by' => $actorName,
                    'ip_address' => request()?->ip() ?? 'N/A',
                ]
            );
        }
    }

    /**
     * Check and alert on large data exports.
     */
    public function checkSensitiveExport(string $exportType, int $recordCount, ?User $actor = null): void
    {
        $exportThreshold = (int) config('audit.large_export_threshold', 500);

        if ($recordCount >= $exportThreshold) {
            $actorName = $actor ? "{$actor->name} ({$actor->email})" : 'Automated';

            $this->dispatchAlert(
                anomalyType: 'mass_data_export',
                title: "High-Volume Data Export ({$recordCount} records)",
                description: "A large data export of type '{$exportType}' containing {$recordCount} records was generated by {$actorName}.",
                metadata: [
                    'export_type' => $exportType,
                    'records_count' => $recordCount,
                    'exported_by' => $actorName,
                    'ip_address' => request()?->ip() ?? 'N/A',
                ]
            );
        }
    }

    /**
     * Dispatch the alert to Super Admins and configured alert email.
     */
    public function dispatchAlert(string $anomalyType, string $title, string $description, array $metadata = []): void
    {
        $notification = new SecurityAnomalyAlert($anomalyType, $title, $description, $metadata);

        // 1. Send to configured dedicated alert email if set
        $alertEmail = config('audit.alert_email', env('AUDIT_ALERT_EMAIL'));
        if ($alertEmail) {
            Notification::route('mail', $alertEmail)->notify($notification);
        }

        // 2. Also notify active admin users in the database
        try {
            $admins = User::where(function ($q) {
                if (Schema::hasColumn('users', 'role')) {
                    $q->whereIn('role', ['admin', 'super-admin', 'superadmin']);
                }
            })->limit(5)->get();

            if ($admins->isNotEmpty()) {
                Notification::send($admins, $notification);
            }
        } catch (\Throwable $e) {
            // In case of test or unmigrated schema, fallback cleanly
        }
    }
}
