[program:bbb-tracker-worker]
process_name=%(program_name)s_%(process_num)02d
directory=/var/www/bbb-tracker
command=php artisan queue:work --queue=default --sleep=3 --tries=3 --backoff=60 --max-time=3600 --timeout=120 --memory=256
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/log/supervisor/bbb-tracker-worker.log
stopwaitsecs=3600
